# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '6-Nhatky' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 6-Nhatky
pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  target '6-NhatkyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '6-NhatkyUITests' do
    # Pods for testing
  end

end
