# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '10-UseRedux' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'ReSwift'
  # Pods for 10-UseRedux

  target '10-UseReduxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '10-UseReduxUITests' do
    # Pods for testing
  end

end
